export {
  ArrayFunc,
  createArr,
  createArr2,
  randomSort,
  removeDuplicates,
  intersection,
  indexOfMax,
  indexOfMin,
  closest,
  zip,
  transpose,
  average,
} from './array'
export { ColorFunc, getRandomColor, hexToRgb } from './color'
export { FunctionFunc, isAsyncFunction } from './function'
export { MathFunc, anagrams, toDecimal, toFixed, round, replenishZero } from './math'
export { ObjectFunc, removeNullUndefined, invert, isEqualObject } from './object'
export { OtherFunc, sleep } from './other'
export { RandomFunc, randomIp, uuid } from './random'
export { RegexFunc, formatPhone, setTrimOut } from './regex'
export { StringFunc, capitalizeEveryWord, capitalize } from './string'
export {
  TimeFunc,
  isToday,
  formatYmd,
  formatSeconds,
  getFirstDate,
  getLastDate,
  getDaysNum,
} from './time'
export {
  WebFunc,
  reload,
  goToTop,
  scrollToTop,
  scrollToBottom,
  isIE,
  stripHtml,
  goTo,
  copyText,
} from './web'

export default {
  ArrayFunc,
  ColorFunc,
  FunctionFunc,
  MathFunc,
  ObjectFunc,
  OtherFunc,
  RandomFunc,
  RegexFunc,
  StringFunc,
  TimeFunc,
  WebFunc,
  createArr,
  createArr2,
  randomSort,
  removeDuplicates,
  intersection,
  indexOfMax,
  indexOfMin,
  closest,
  zip,
  transpose,
  average,
  getRandomColor,
  hexToRgb,
  isAsyncFunction,
  anagrams,
  toDecimal,
  toFixed,
  round,
  replenishZero,
  removeNullUndefined,
  invert,
  isEqualObject,
  sleep,
  randomIp,
  uuid,
  formatPhone,
  setTrimOut,
  capitalizeEveryWord,
  capitalize,
  isToday,
  formatYmd,
  formatSeconds,
  getFirstDate,
  getLastDate,
  getDaysNum,
  reload,
  goToTop,
  scrollToTop,
  scrollToBottom,
  isIE,
  stripHtml,
  goTo,
  copyText,
}
