import {
  Array,
  createArr,
  createArr2,
  randomSort,
  removeDuplicates,
  intersection,
  indexOfMax,
  indexOfMin,
  closest,
  zip,
  transpose,
  average,
} from './array'
import { Color, getRandomColor, hexToRgb } from './color'
import { Function, isAsyncFunction } from './function'
import { Math, anagrams, toDecimal, toFixed, round, replenishZero } from './math'
import { Object, removeNullUndefined, invert, isEqualObject } from './object'
import { Other, sleep } from './other'
import { Random, randomIp, uuid } from './random'
import { Regex, formatPhone, setTrimOut } from './regex'
import { String, capitalizeEveryWord, capitalize } from './string'
import {
  Time,
  isToday,
  formatYmd,
  formatSeconds,
  getFirstDate,
  getLastDate,
  getDaysNum,
} from './time'
import {
  reload,
  goToTop,
  scrollToTop,
  scrollToBottom,
  isIE,
  stripHtml,
  goTo,
  copyText,
  Web,
} from './web'

export default {
  Array,
  Color,
  Function,
  Math,
  Object,
  Other,
  Random,
  Regex,
  String,
  Time,
  Web,
  createArr,
  createArr2,
  randomSort,
  removeDuplicates,
  intersection,
  indexOfMax,
  indexOfMin,
  closest,
  zip,
  transpose,
  average,
  getRandomColor,
  hexToRgb,
  isAsyncFunction,
  anagrams,
  toDecimal,
  toFixed,
  round,
  replenishZero,
  removeNullUndefined,
  invert,
  isEqualObject,
  sleep,
  randomIp,
  uuid,
  formatPhone,
  setTrimOut,
  capitalizeEveryWord,
  capitalize,
  isToday,
  formatYmd,
  formatSeconds,
  getFirstDate,
  getLastDate,
  getDaysNum,
  reload,
  goToTop,
  scrollToTop,
  scrollToBottom,
  isIE,
  stripHtml,
  goTo,
  copyText,
}
